exp_name: duie # nyt_star, nyt, webnlg_star, webnlg, ace05_lu
data_in_dir: ori_data
ori_data_format: duie_format # casrel (webnlg_star, nyt_star), etl_span (webnlg), raw_nyt (nyt), tplinker (see readme)

# 如果为BERT建立数据，使用这3行，并注释下面2行。
encoder: BERT
bert_path: pretrained_models/chinese-bert-wwm-ext #  chinese-bert-wwm-ext, bert-base-cased
data_out_dir: data4bert

# # if build data for BiLSTM, use these 2 lines and comment above 3 lines.
# encoder: BiLSTM
# data_out_dir: ../data4bilstm

# 如果只是复制结果，不需要改变下面的args。
# separate_char_by_white: e.g. "$%sdkn839," -> "$% sdkn839 ," , will make original char spans invalid, 中文也设置false
# add_char_span: 如果它已经存在，则将add_char_span设置为false。
# ignore_subword: 当添加字符级别的跨度时，匹配周围有空白的单词。"word"，为了避免子词匹配，对中文设置为false。查找周围有空格的实体
# check_tok_span: 检查token跨度是否有错误，如果有，打印未匹配信息。
# 中文的数据，需要移除空格
add_char_span: true
ignore_subword: false
separate_char_by_white: false
remove_white_space: true
check_tok_span: true
